[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"
targetPort = 3000
port = 3001

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/*"

[headers.values]
Cache-Control = "public, max-age=3600"

[images]
  remote_images = ["https://cdn.shopify.com/.*", "https://images.e-lationshop.com/.*"]

