[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"
targetPort = 3000
port = 3001

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
for = "/*.(webp|jpg|png|gif)"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

[images]
  remote_images = ["https://cdn.shopify.com/.*", "https://images.e-lationshop.com/.*"]

